apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 30050 # NodePort range is 30000-32767
    - name: websocket
      protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30051
