apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      nodeSelector:  # Ensure the pod is scheduled on the server node
        kubernetes.io/hostname: "ip-172-31-1-199"  # Replace with the desired node name
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090