apiVersion: v1
kind: PersistentVolume
metadata:
  name: timescaledb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/timescaledb  # Path on the node where data will be stored
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "ip-172-31-1-199"  # Ensure the PV is bound to this node