apiVersion: v1
kind: Pod
metadata:
  name: sqlite-pod
spec:
  containers:
  - name: sqlite-container
    image: nouchka/sqlite3:latest
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    volumeMounts:
    - name: sqlite-data
      mountPath: /data
  nodeSelector:
    disktype: ssd
  volumes:
  - name: sqlite-data
    persistentVolumeClaim:
      claimName: sqlite-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/sqlite-data  # Path on the node where data will be stored