apiVersion: v1
kind: Pod
metadata:
  name: resource-aware-pod
spec:
  containers:
  - name: app-container
    image: your-app-image
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
  nodeSelector:
    disktype: ssd